### ISSUE TITLE
kanban review

### ISSUE THREAD

**Issue by mohamed20163858** [mohamed20163858/Catalog-of-my-things#20]
# Honorable Code Reviewer,

<div style="width:100%;height:0;padding-bottom:100%;position:relative;"><img src="https://media.giphy.com/media/Jfa07ySDdvmFzeqCek/giphy.gif" width="100%" height="100%" style="position:absolute"></img></div>

## In this PR, the following tasks have been completed: 
We created a [kanban board for the ruby capstone project](https://github.com/mohamed20163858/Catalog-of-my-things/projects/1) and the group team is consist of 2 team members which are:- 
1) [Mohamed Saleh](https://github.com/mohamed20163858)
2) [Omar Warrish](https://github.com/OmarMWarraich) 
 
Here are the responsibilities assigned to each member of the team:- 

## [Mohamed Saleh](https://github.com/mohamed20163858) Responsibilities
- Create a Book class in a separate .rb file
- Create a Label class with an association to the Item class in a separate .rb file 
-  Implement methods: can_be_archived?() in the Book class 
- Implement methods: add_item method in the Label class 
-  Add unit tests for all implemented methods
-  Preserve Data
- Create a schema.sql file with tables that will be analogical to the structure of the classes created

## [Omar Warrish](https://github.com/OmarMWarraich)  Responsibilities 
- Create a MusicAlbum class in a separate .rb file
- Implement methods: can_be_archived?() in the MusicAlbum class
-  Create a Genre class with an association to the Item class in a separate .rb file
-  Implement methods: add_item method in the Genre class
-  Add unit tests for all implemented methods
-  Preserve Data
- Create a schema.sql file with tables that will be analogical to the structure of the classes created

**Comment by KDlamini** [comment]
## Status: Invalid 🔴 

### Hi @mohamed20163858  🙋‍♀️,  

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request
 
You have submitted an issue for the Kanban Board using the Group Capstone link. Please submit the final `Pull Request` of your project merging the `dev` branch to the `main`. The pull request should have a recorded presentation video and commits from all members of the group.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._
